import sqlite3
import os
import shutil
import sys

def main():
    db_path = "config/library.db"
    if not os.path.exists(db_path):
        db_path = "library.db"
        if not os.path.exists(db_path):
            print("Database config/library.db or library.db not found!")
            sys.exit(1)
            
    backup_path = db_path + ".bak"
    recovered_path = db_path + ".recovered"
    
    print(f"Starting database recovery...")
    # Check if backup exists, if not create one. If it does, we use it as the source.
    if not os.path.exists(backup_path):
        print(f"Creating backup of original database at: {backup_path}")
        shutil.copy2(db_path, backup_path)
    else:
        print(f"Backup already exists at: {backup_path}. We will recover from this backup.")
    
    try:
        # Connect to the backup database to dump (safe from WAL locks)
        conn = sqlite3.connect(backup_path)
        
        # Dump the schema and data to SQL statements
        print("Dumping schema and data to SQL script from backup...")
        sql_dump = []
        for line in conn.iterdump():
            # Skip transaction commands generated by iterdump so we manage them ourselves
            if line.startswith("BEGIN TRANSACTION") or line.startswith("COMMIT"):
                continue
            sql_dump.append(line)
        conn.close()
        
        # Create fresh recovered database
        print(f"Rebuilding database at: {recovered_path}")
        if os.path.exists(recovered_path):
            os.remove(recovered_path)
            
        new_conn = sqlite3.connect(recovered_path)
        cursor = new_conn.cursor()
        
        # Execute the dumped SQL statements to rebuild the database
        cursor.execute("BEGIN TRANSACTION;")
        for statement in sql_dump:
            try:
                cursor.execute(statement)
            except sqlite3.Error as e:
                # Log any errors but keep going to save as much data as possible
                if "UNIQUE constraint failed" not in str(e):
                    print(f"Warning: Skipped statement due to error: {e}")
        
        new_conn.commit()
        
        # Verify integrity of recovered database
        print("Verifying integrity of recovered database...")
        cursor.execute("PRAGMA integrity_check")
        result = cursor.fetchall()
        print(f"Integrity Check Result: {result}")
        new_conn.close()
        
        if result == [('ok',)]:
            print("Integrity check PASSED!")
            
            # Swap the database files and delete WAL/SHM files
            print("Deleting old database and journal files...")
            
            # Remove main db
            if os.path.exists(db_path):
                os.remove(db_path)
                
            # Crucial step: Remove WAL and SHM files to prevent re-corrupting the new DB
            for ext in ["-wal", "-shm"]:
                journal_file = db_path + ext
                if os.path.exists(journal_file):
                    os.remove(journal_file)
                    print(f"Removed old journal file: {journal_file}")
                    
            print("Swapping recovered database into place...")
            os.rename(recovered_path, db_path)
            print("Database recovery completed successfully!")
        else:
            print("Error: The recovered database is still reported as corrupted by SQLite.")
            print(f"Details: {result}")
            print("Aborting database swap. Your original file remains untouched.")
            sys.exit(1)
            
    except Exception as e:
        print(f"An error occurred during recovery: {e}")
        if os.path.exists(recovered_path):
            try:
                os.remove(recovered_path)
            except Exception:
                pass
        sys.exit(1)

if __name__ == "__main__":
    main()
