import sqlite3
import os
import shutil
import sys

def main():
    db_path = "config/library.db"
    if not os.path.exists(db_path):
        db_path = "library.db"
        if not os.path.exists(db_path):
            print("Database config/library.db or library.db not found!")
            sys.exit(1)
            
    backup_path = db_path + ".bak"
    recovered_path = db_path + ".recovered"
    
    print(f"Starting database recovery for {db_path}...")
    print(f"Creating backup of original database at: {backup_path}")
    shutil.copy2(db_path, backup_path)
    
    try:
        # Connect to corrupted database
        conn = sqlite3.connect(db_path)
        
        # Dump the schema and data to SQL statements
        print("Dumping schema and data to SQL script...")
        sql_dump = []
        for line in conn.iterdump():
            # Skip transaction commands generated by iterdump so we manage them ourselves
            if line.startswith("BEGIN TRANSACTION") or line.startswith("COMMIT"):
                continue
            sql_dump.append(line)
        conn.close()
        
        # Create fresh recovered database
        print(f"Rebuilding database at: {recovered_path}")
        if os.path.exists(recovered_path):
            os.remove(recovered_path)
            
        new_conn = sqlite3.connect(recovered_path)
        cursor = new_conn.cursor()
        
        # Execute the dumped SQL statements to rebuild the database
        cursor.execute("BEGIN TRANSACTION;")
        for statement in sql_dump:
            try:
                cursor.execute(statement)
            except sqlite3.Error as e:
                # Log any errors but keep going to save as much data as possible
                print(f"Warning: Skipped statement due to error: {e}\nStatement: {statement[:100]}...")
        
        new_conn.commit()
        
        # Verify integrity of recovered database
        print("Verifying integrity of recovered database...")
        cursor.execute("PRAGMA integrity_check")
        result = cursor.fetchall()
        print(f"Integrity Check Result: {result}")
        new_conn.close()
        
        if result == [('ok',)]:
            print("Integrity check PASSED!")
            
            # Swap the database files
            print("Swapping old database with recovered database...")
            # Close any connections in the app if necessary. In Docker, it's best to stop the app first,
            # but since we are running via kubectl exec, we will replace the file directly.
            os.remove(db_path)
            os.rename(recovered_path, db_path)
            print("Database recovery completed successfully!")
        else:
            print("Error: The recovered database is still reported as corrupted by SQLite.")
            print(f"Details: {result}")
            print("Aborting database swap. Your original file remains untouched.")
            sys.exit(1)
            
    except Exception as e:
        print(f"An error occurred during recovery: {e}")
        if os.path.exists(recovered_path):
            try:
                os.remove(recovered_path)
            except Exception:
                pass
        sys.exit(1)

if __name__ == "__main__":
    main()
