"""Add rich metadata fields

Revision ID: 0356439e54ae
Revises: 5a15aa3bb629
Create Date: 2026-02-15 22:59:37.565923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0356439e54ae'
down_revision: Union[str, Sequence[str], None] = '4ed83310b437'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('description', sa.String(), nullable=True))
    op.add_column('stories', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('stories', sa.Column('rating', sa.String(), nullable=True))
    op.add_column('stories', sa.Column('language', sa.String(), nullable=True))
    op.add_column('stories', sa.Column('publication_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'publication_status')
    op.drop_column('stories', 'language')
    op.drop_column('stories', 'rating')
    op.drop_column('stories', 'tags')
    op.drop_column('stories', 'description')
    # ### end Alembic commands ###
