"""Update DownloadHistory

Revision ID: 068070344237
Revises: 20260222_add_chapter_tags
Create Date: 2026-02-27 09:39:53.684889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '068070344237'
down_revision: Union[str, Sequence[str], None] = '20260222_add_chapter_tags'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_history') as batch_op:
        batch_op.add_column(sa.Column('event_type', sa.String(), server_default='download', nullable=True))
        batch_op.alter_column('chapter_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('story_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('download_history', 'story_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('download_history', 'chapter_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('download_history', 'event_type')
    # ### end Alembic commands ###
