"""Add discord_channel_name

Revision ID: b8124481556f
Revises: ca79879d6478
Create Date: 2026-03-24 17:41:31.851550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8124481556f'
down_revision: Union[str, Sequence[str], None] = 'ca79879d6478'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('discord_channel_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'discord_channel_name')
    # ### end Alembic commands ###
