"""Add discord_channel_id

Revision ID: ca79879d6478
Revises: 068070344237
Create Date: 2026-03-24 15:35:16.162485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca79879d6478'
down_revision: Union[str, Sequence[str], None] = '068070344237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('discord_channel_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'discord_channel_id')
    # ### end Alembic commands ###
